# NOTE: this should be in gitignore, added to git for structure so change secrets data
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: metrics-dashboard
type: Opaque
data:
  # Base64 encoded secrets (echo -n "password" | base64)
  database-password: cGFzc3dvcmQ=
  rails-secret-key-base: cGFzc3dvcmQ=
